### ISSUE TITLE
Create Infrastructure for Turn-Based Features

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#73]
Currently, our data are analyzed at two levels:
1. The **chat** level, e.g., each individual message;
2. The **conversation** level, e.g., all of the messages that were shared during a given group/round.

However, in general, conversations can be analyzed at a *turn* level --- that is, when people have conversations, they tend to speak in "turns." The pattern of turn-taking in conversation is often considered a useful indicator.

Good reference: https://arxiv.org/pdf/2203.00674.pdf

We currently do not have the ability to account for turn-by-turn features, or even measure what constitutes a "turn." The purpose of this Issue is to explore (and potentially implement) turn-based features.

# Stage 0: Default
The default "turn" is just a single chat. This requires no action on our part. It might be helpful to have a function that essentially does nothing (returns the original dataframe) just so that we can set up this function for the future.

# Stage 1: Exploration & Basic Implementation
The next stage is to explore whether we should do any grouping together of features. Here are three quick sanity checks:

- [ ] Start with the histogram of turns. If it is bimodal (e.g., people either send message in quick succession, or take a while between messages), then we can split messages into turns based on timing; if not, then perhaps it is not useful.
- [ ] Start with measuring how often this happens --- in other words, how often are people 'interrupted'? And how often do people send multiple messages in a row, per conversation?
- [ ] Another test: try reversing the order or scrambling the conversations. Then check that any turn-level features are even sensitive to those changes; if not, then it may not matter (those features may not contain any signal at all).

After running these sanity checks, we can start with a basic implementation:
- [ ] Bucket only *promixmal chats: look at turn-based features in C.18: it just automatically bucketed something if it was continuous (e.g., the same person posted back-to-back).

Check back in after running the Sanity checks, and we can plan a design for more advanced Turn detection based on those results.

**Comment by xehu** [comment]
@agshruti12 pasting notes from today:
- Start by grouping together consecutive turns as a preprocessing step (e.g., in `preprocessing.py`)
- For consecutive messages by the same person, combined into 1 turn, we can just consider the first timestamp as the “start” of their turn (since that’s when they started speaking)

Potential Upcoming Concerns:
- Timestamps: if we combine multiple interlaced turns, what do we do with the timestamp?

Up next: Adding turn-based features / improving style accommodation features
- Ex: How are people ‘echoing back’ features from other users on a turn-by-turn basis?
- (Example Paper) Mark My Words! Linguistic Style Accommodation in Social Media https://arxiv.org/pdf/1105.0673.pdf
- Reference – existing mimicry feature (which we can move to the conversation level):
https://github.com/Watts-Lab/team-process-map/blob/main/feature_engine/features/word_mimicry.py

**Comment by agshruti12** [comment]
Preprocessing naive turns done - combines adjacent chats of same speaker within a given conversation and takes the first timestamp. Cannot full yet due to lack of BERT embeddings specifically generated for the combined chats... could go for an average approach, although there would be some data loss...

**Comment by xehu** [comment]
@agshruti12 this makes sense!

It suggests to me that we just need new SBERT vectors to run on the turn-by-turn basis? Like we should just run a new pre-processing step once the turns are combined. Then we'll have the vectors and everything will proceed as normal, right?

I wonder if it makes sense to partially implement this issue while we're at it: https://github.com/Watts-Lab/team-process-map/issues/137

In other words, when we run `featurize.py`, it checks for whether it has the SBERT vectors on the dataset, and if not, it just goes ahead and calls the vector-generating script. This process only needs to take place once, and then in the future, we will pass the checking step and everything will go smoothly (without the manual running of the preprocessing notebooks).

The last thing I can think of, which might block merging turns, is the timestamp, although we could just apply the rule of "take the earliest known timestamp" --- since in a real world conversation, that's when you "started" talking.
